import json
import os

class ErrorCode:
    CAMERA_DISCONNECTED = "E1111"
    MOTIONPLATFORM_DISCONNECTED = "E1201"
    EXPOSURE_UNDER = "E2302"
    EXPOSURE_OVER = "E2303"
    GENERIC = "GENERIC"
    CAMERA_STATUS_UNKNOWN = "E9999"

    # Pipeline / Recipe error codes
    PIPELINE_VALIDATION_FAILED = "E3001"
    PIPELINE_TYPE_INCOMPATIBLE = "E3002"
    PIPELINE_PARAM_OUT_OF_RANGE = "E3003"
    PIPELINE_SOURCE_NOT_FOUND = "E3004"
    PIPELINE_STEP_EXECUTION_FAILED = "E3005"
    RECIPE_IO_ERROR = "E3006"
    RECIPE_NOT_FOUND = "E3007"
    RECIPE_INVALID_FORMAT = "E3008"

    # Processing element error codes (E2xxx) — message resolution
    # handled by pipeline_engine.PROC_ELEMENT_MESSAGES, not by
    # error_messages.json, to avoid conflicts with scanner E2xxx codes.
    PE_LOAD_NO_IMAGES = "E2001"
    PE_LOAD_INVALID_PATH = "E2002"
    PE_LOAD_NO_VALID = "E2003"
    PE_LOAD_UNSUPPORTED = "E2004"
    PE_CHANNEL_NO_IMAGES = "E2100"
    PE_CHANNEL_NOT_3CH = "E2101"
    PE_CHANNEL_BAD_SPACE = "E2102"
    PE_CHANNEL_BAD_CHAN = "E2103"
    PE_CHANNEL_CONV_FAIL = "E2104"
    PE_THRESH_NO_IMAGES = "E2201"
    PE_THRESH_NOT_SINGLE = "E2202"
    PE_HIST_NO_IMAGES = "E2301"
    PE_HIST_NOT_GRAY = "E2302"
    PE_HIST_BAD_BINS = "E2303"
    PE_HIST_BAD_RANGE = "E2304"
    PE_HIST_CALC_FAIL = "E2305"
    PE_HIST_UNEXPECTED = "E2306"
    PE_MASK_NO_IMAGES = "E2401"
    PE_MASK_NOT_SINGLE = "E2402"
    PE_MASK_BAD_RANGE = "E2403"
    PE_MASK_UNEXPECTED = "E2404"
    PE_STATS_NO_IMAGES = "E2501"
    PE_STATS_NO_MASKS = "E2502"
    PE_STATS_MISMATCH = "E2503"
    PE_STATS_BAD_PCT = "E2504"
    PE_STATS_NO_PIXELS = "E2505"
    PE_STATS_CALC_FAIL = "E2506"
    PE_STATS_UNEXPECTED = "E2507"
    PE_SEQ_NO_IMAGES = "E2631"
    PE_SEQ_NO_NAME = "E2632"
    PE_SEQ_NO_VALS = "E2633"
    PE_SEQ_BAD_VALS = "E2634"
    PE_SEQ_COUNT_MISMATCH = "E2635"
    PE_SEQ_BAD_STEP = "E2636"
    PE_SEQ_BAD_RANGE = "E2637"
    PE_SEQ_UNEXPECTED = "E2638"
    PE_FIT_NO_IMAGES = "E2701"
    PE_FIT_NO_STATS = "E2702"
    PE_FIT_X_MISSING = "E2703"
    PE_FIT_Y_MISSING = "E2704"
    PE_FIT_FEW_POINTS = "E2705"
    PE_FIT_LEN_MISMATCH = "E2706"
    PE_FIT_NAN_INF = "E2707"
    PE_FIT_FAILED = "E2708"
    PE_FIT_BAD_MODEL = "E2709"
    PE_FIT_HIGH_DEGREE = "E2710"
    PE_FIT_UNEXPECTED = "E2711"
    PE_PRED_NO_MODEL = "E2801"
    PE_PRED_NO_FITS = "E2803"
    PE_PRED_BAD_INDEX = "E2804"
    PE_PRED_NO_STATS = "E2805"
    PE_PRED_CALC_FAIL = "E2806"
    PE_PRED_UNEXPECTED = "E2808"

def load_error_messages():
    file_path = os.path.join(os.path.dirname(__file__), "error_messages.json")
    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)

ERROR_MESSAGES = load_error_messages()